version: '3'
services:
  postgres:
    image: postgres:12
    networks:
      - app_backend
    container_name: goit_llm_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#  test_db:
#    image: postgres:12
#    networks:
#      - app_backend
#    container_name: test_db
#    restart: always
#    environment:
#      POSTGRES_DB: test_db
#      POSTGRES_USER: test_user
#      POSTGRES_PASSWORD: 567234
#    ports:
#      - "5433:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/goit_llm
      - ./docker:/goit_llm/docker
      - ./migrations:/goit_llm/migrations
      - ./alembic.ini:/goit_llm/alembic.ini
      - ./.env:/goit_llm
    restart: always
    env_file:
      - .env
    container_name: goit_llm
    networks:
      - app_backend
#    command: "alembic upgrade head"
    ports:
      - 8000:8000
    depends_on:
      - postgres

networks:
  app_backend:
    driver: bridge
